### ISSUE TITLE
右键菜单栏有没有填写链接地址的功能啊？

### ISSUE THREAD

**Issue by zgpnuaa** [ssshooter/mind-elixir-core#109]
目前只能在代码后台填写链接地址，在右键菜单栏没有找到填写链接地址的地方。

![右键超链接](https://user-images.githubusercontent.com/38033949/178518441-4026fd25-824c-4dab-8aae-f8a84165c28d.png)

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/178629649-90d63449-89e2-447a-a478-cf719bdbc0bb.png)

在这里
