### ISSUE TITLE
text over flow issue

### ISSUE THREAD

**Issue by HumbleDev-1119** [ssshooter/mind-elixir-core#115]
I'm using mind-elixir library for my mind map app. but I can't fix this issue. 
![Screenshot_1](https://user-images.githubusercontent.com/32957829/181904299-614734da-ed84-4fce-99f7-78acd6f6e790.png)
please help me.

**Comment by ssshooter** [comment]
Typically speaking, there is no single word longer than 800px so that this problem won't occur……Try adding a whitespace between those `1` and it will wrap.
