### ISSUE TITLE
image cutting issue

### ISSUE THREAD

**Issue by HumbleDev-1119** [ssshooter/mind-elixir-core#116]
I've typed long text and then got image by using painter.exportPng(). but it's cut image. the below image is mind map.
In the map, it's showing multi lines.
![image](https://user-images.githubusercontent.com/32957829/181919121-b293359e-91f1-49df-ab46-85f43bae657c.png)
 
 it's showing one line at an exported image. here is cut image
![62e536c05ffe58775acaa64e](https://user-images.githubusercontent.com/32957829/181919200-01baf4bb-3f49-4586-8c2f-a9cb238bcbb9.jpg)
how can I get solved this issue?

**Comment by ssshooter** [comment]
This function is working in progress. To fix it, you could wrap the text manually.

https://github.com/ssshooter/mind-elixir-core/blob/6c18ece1dde35de1d5f89a1caf20ab4ae79248af/painter/index.js#L179
