### ISSUE TITLE
关于linkdata变更事件监听器

### ISSUE THREAD

**Issue by huangxy29** [ssshooter/mind-elixir-core#120]
您好，最近使用了您的这个项目，真的是很厉害👍，当然，我就不在这里赘述了。我在使用中碰到了一个问题，希望能得到您的帮助：

我使用了operation添加事件监听，但是其中并不包含link变更，添加/删除 link 后不会触发事件，link的变更有自己的event listener吗？或者nodeOperations的listener中能增加link变更的监听事件吗？

最后祝您生活愉快。

**Comment by ssshooter** [comment]
最近比较忙，如果你急得话直接在这里 `this.bus.fire('createLink ')` 就好了😥

https://github.com/ssshooter/mind-elixir-core/blob/6c18ece1dde35de1d5f89a1caf20ab4ae79248af/src/customLink.ts#L117

**Comment by huangxy29** [comment]
> 最近比较忙，如果你急得话直接在这里 `this.bus.fire('createLink ')` 就好了😥
> 
> https://github.com/ssshooter/mind-elixir-core/blob/6c18ece1dde35de1d5f89a1caf20ab4ae79248af/src/customLink.ts#L117

十分感谢🙏
