### ISSUE TITLE
线条的美观度 有没有办法调整

### ISSUE THREAD

**Issue by tanyo520** [ssshooter/mind-elixir-core#122]
线条的美观度，和线条自定义的位置有没有办法调整

**Comment by ssshooter** [comment]
暂时没有接口可以改子节点连线，根节点连线只有两种样式，修改 `primaryLinkStyle` 可设置。当然也可以自己随便改，代码位置如下：

根节点连线：
https://github.com/ssshooter/mind-elixir-core/blob/6c18ece1dde35de1d5f89a1caf20ab4ae79248af/src/linkDiv.ts#L90
子节点连线：
https://github.com/ssshooter/mind-elixir-core/blob/6c18ece1dde35de1d5f89a1caf20ab4ae79248af/src/linkDiv.ts#L199

**Comment by tanyo520** [comment]
> 暂时没有接口可以改子节点连线，根节点连线只有两种样式，修改 `primaryLinkStyle` 可设置。当然也可以自己随便改，代码位置如下：
> 
> 根节点连线：
> 
> https://github.com/ssshooter/mind-elixir-core/blob/6c18ece1dde35de1d5f89a1caf20ab4ae79248af/src/linkDiv.ts#L90
> 
> 
> 子节点连线：
> https://github.com/ssshooter/mind-elixir-core/blob/6c18ece1dde35de1d5f89a1caf20ab4ae79248af/src/linkDiv.ts#L199

感谢
