### ISSUE TITLE
Trouble with install

### ISSUE THREAD

**Issue by Alexyoe** [ssshooter/mind-elixir-core#129]
I'm having trouble getting mind-elixir setup. I've tried setting up a simple html document with a script tag to the CDN but always get the error "Uncaught ReferenceError: MindElixir is not defined". I've also tried duplicating the demo at https://codepen.io/ssshooter/pen/GVQRYK but I get the same error when running it locally. 

Any help would be appreciated!

**Comment by ssshooter** [comment]
Sorry, the readme file is outdated; I updated it just now.

```html
<script src="https://cdn.jsdelivr.net/npm/mind-elixir/dist/MindElixir.js"></script>
```
