### ISSUE TITLE
vue3 setup语法使用时提示init is not a function

### ISSUE THREAD

**Issue by tqq1994516** [ssshooter/mind-elixir-core#146]
```vue3
<template>
  <div id="map" class="map"></div>
</template>
<script lang="ts" setup>
  import MindElixir from 'mind-elixir';
  import { onMounted, ref } from 'vue';

  const me = ref<MindElixir>();
  onMounted(() => {
    me.value = new MindElixir({
      el: '#map',
      direction: MindElixir.LEFT,
    });
    me.value.init(MindElixir.new('demo'));
  });
</script>
<style lang="less" scoped>
  .map {
    width: 100%;
    height: 500px;
  }
</style>
```
在我尝试使用vue3.2中setup语法使用mind-elixir时，一直提示init is not a function
![image](https://user-images.githubusercontent.com/61398122/207833424-096c8763-a2b3-49c2-9587-979c4777828e.png)

**Comment by ssshooter** [comment]
https://codesandbox.io/s/mind-elixir-vue3-dtcq6u?file=/src/components/HelloWorld.vue

应该没有问题，报错里是 `me.init`，但是代码不是 `me.value.init` 吗？

**Comment by tqq1994516** [comment]
> https://codesandbox.io/s/mind-elixir-vue3-dtcq6u?file=/src/components/HelloWorld.vue
> 
> 应该没有问题，报错里是 `me.init`，但是代码不是 `me.value.init` 吗？

之前是没有加`ref`函数所以是没有`.value`,我尝试之前没有把这个作为组件引入  我再尝试下

**Comment by tqq1994516** [comment]
> lang="ts"

怀疑是ts语法导致的

**Comment by ssshooter** [comment]
> > lang="ts"
> 
> 怀疑是ts语法导致的

ts 编译总不会把函数给整没吧😂

**Comment by tqq1994516** [comment]
> ts 编译总不会把函数给整没吧😂
应该还是我使用问题，换成组件引用已经可以了

**Comment by ChuanQiZhu** [comment]
我也遇到这个问题了，问下您是怎么解决的啊？
