### ISSUE TITLE
加自定义节点

### ISSUE THREAD

**Issue by Rangowj** [ssshooter/mind-elixir-core#152]
您好，咱们这个插件可以在点击的节点处加自定义节点吗，如果可以，又是如果插入呢

**Comment by ssshooter** [comment]
怎么定义自定义节点？

**Comment by Rangowj** [comment]
> 怎么定义自定节点？
简单的html标签，或者通过addChild(nodeObj)传参形式添加节点

**Comment by Rangowj** [comment]
比如icon + text，icon在前，text在后

**Comment by ssshooter** [comment]
现在没有提供修改节点渲染函数的方法，但是可以根据自己需求改这里

https://github.com/ssshooter/mind-elixir-core/blob/acf65cff947fb538c41d273ca1a44413e33a29ec/src/utils/dom.ts#L24

**Comment by Rangowj** [comment]
> 现在没有提供修改节点渲染函数的方法，但是可以根据自己需求改这里
> 
> https://github.com/ssshooter/mind-elixir-core/blob/acf65cff947fb538c41d273ca1a44413e33a29ec/src/utils/dom.ts#L24
