### ISSUE TITLE
Node Menu is disappeared 

### ISSUE THREAD

**Issue by asith-w** [ssshooter/mind-elixir-core#171]
after updating nice colorful newer version(2.0.1), node menu is disappeared . is there any reason for that or is it a plugin now ?

https://codepen.io/ssshooter/pen/rNqGpwW

**Comment by ssshooter** [comment]
It's not a  build in plugin now, but the good new is you can customize it more easily. See https://github.com/ssshooter/node-menu

**Comment by asith-w** [comment]
> It's not a build in plugin now, but the good new is you can customize it more easily. See https://github.com/ssshooter/node-menu

but it is not working as expected https://codesandbox.io/s/mind-elixir-2-x-react-q9glxt

**Comment by ssshooter** [comment]
> > It's not a build in plugin now, but the good new is you can customize it more easily. See https://github.com/ssshooter/node-menu
> 
> but it is not working as expected https://codesandbox.io/s/mind-elixir-2-x-react-q9glxt

Sorry, `import "@mind-elixir/node-menu/dist/style.css";` is missing.

**Comment by asith-w** [comment]
![image](https://user-images.githubusercontent.com/5784846/236698787-22aaa935-3c38-44ba-b7aa-9e05ac785cc5.png)
however this menu reopen button is hidden once  we close the node menu
