### ISSUE TITLE
vue3 版本，样式问题

### ISSUE THREAD

**Issue by chenwynn** [ssshooter/mind-elixir-core#173]
本地安装的VUE3 的版本，导入的example 的 js 的文件，发现 theme 没有生效；

### HelloWorld.vue

```vue
<template>
  <div id="map"></div>
</template>
<script setup>
import MindElixir from "mind-elixir";
import { onMounted, ref } from "vue";
import example from  './1';    

const me = ref();
onMounted(() => {
  me.value = new MindElixir({
    el: "#map",
    direction: MindElixir.SIDE,
    mainLinkStyle: 1,
    mainNodeVerticalGap: 25, // 25
    mainNodeHorizontalGap: 65, // 65
    draggable: true,
    editable: true,
    contextMenu: true,
    toolBar: true,
    nodeMenu: true,
    keypress: true,
  });
  me.value.init(example);
});
</script>
<style lang="less" scoped>
#map {
  width: 100%;
  height:1000px;
}
</style>
```

**本地样式**

<img width="1500" alt="截屏2023-05-07 22 47 45" src="https://user-images.githubusercontent.com/7459563/236684741-657552fc-5f78-4d91-a6f6-6d97f70df333.png">

### 目标样式：

<img width="1262" alt="截屏2023-05-07 22 48 40" src="https://user-images.githubusercontent.com/7459563/236684757-cf93f698-1f4a-4c2d-bc8d-42d29a37c3f2.png">

该如何配置，或者如何实现呢？

**Comment by ssshooter** [comment]
下面的图片是2.x的样式，你npm install的应该是1.x，但是 1.x 样式错误确实有点奇怪，问题可能是你本地样式文件覆盖了节点样式

**Comment by chenwynn** [comment]
> 

那我重新 npm install 一下试试看；
