### ISSUE TITLE
节点A移动节点B时（单次），moveNodeAfter或者moveNodeBefore被调用多次问题

### ISSUE THREAD

**Issue by ChuanQiZhu** [ssshooter/mind-elixir-core#174]
节点A移动节点B时（单次），moveNodeAfter或者moveNodeBefore被调用了多次，有什么办法只调用一次吗？

**Comment by ssshooter** [comment]
能提供重现链接吗？

**Comment by ChuanQiZhu** [comment]
找到原因了，是因为在渲染不同脑图数据结构的过程中，做了多次init操作导致的。多次init会导致这些问题的发生
