### ISSUE TITLE
Tags are not correctly format for root node

### ISSUE THREAD

**Issue by asith-w** [ssshooter/mind-elixir-core#175]
Tags are not correctly format for root node
![image](https://github.com/ssshooter/mind-elixir-core/assets/5784846/1cbf791e-85e5-482d-b3ff-37f84776c838)
https://codesandbox.io/s/mind-elixir-2-x-react-q9glxt?file=/index.js

**Comment by Mikuu** [comment]
same issue here, actually the style attribute to the root node is totally unhandled.
<img width="1780" alt="Screen Shot 2023-07-05 at 1 46 25 PM" src="https://github.com/ssshooter/mind-elixir-core/assets/11648253/1711d3cf-cdf1-42a0-8714-a7e7ad272b60">
