### ISSUE TITLE
能否支持在2.0版本导出图片？

### ISSUE THREAD

**Issue by pengxx1758** [ssshooter/mind-elixir-core#177]

**Comment by ssshooter** [comment]
短时间内不支持，能接受导出html的话可以试试[@mind-elixir/export-html](https://github.com/ssshooter/export-html)🥺

**Comment by pengxx1758** [comment]
> 短时间内不支持，能接受导出html的话可以试试[@mind-elixir/export-html](https://github.com/ssshooter/export-html)🥺

好的，感谢
