### ISSUE TITLE
有没有办法调整Tag标签的位置

### ISSUE THREAD

**Issue by bluesaiz** [ssshooter/mind-elixir-core#179]
如下图的标签，我想把Tag标签放在节点的最前面，有办法支持吗？或者有什么配置项可以支持吗？谢谢
![image](https://github.com/ssshooter/mind-elixir-core/assets/40681310/10482dd9-ab2b-40b1-8b18-5fc2289fcd77)

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/44a36f228f70ef2aac4b2c82f6d8c108043359b5/src/utils/dom.ts#L53

可以改源码，但是不好改，文字和tag的顺序会对一些节点操作造成影响

**Comment by bluesaiz** [comment]
@ssshooter 哦，好的，谢谢，会对哪些操作有影响？

**Comment by ssshooter** [comment]
对节点内容的操作有影响，节点增删应该正常

**Comment by bluesaiz** [comment]
好的，谢谢
