### ISSUE TITLE
如何支持对移动端的预览，不做编辑

### ISSUE THREAD

**Issue by tanyo520** [ssshooter/mind-elixir-core#180]
如何支持对移动端的预览，不做编辑

**Comment by ssshooter** [comment]
options 里 editable 设为 false

**Comment by tanyo520** [comment]
大佬，求加微信12338947，我们将mind-elixir用于产品了，看看后期是否可以合作。

**Comment by tanyo520** [comment]
> 大佬，求加微信12338947，我们将mind-elixir用于产品了，看看后期是否可以合作。
