### ISSUE TITLE
2.0.2版本特殊结构连线有瑕疵

### ISSUE THREAD

**Issue by tigerxiongj** [ssshooter/mind-elixir-core#181]

**Comment by tigerxiongj** [comment]
没法截图
main节点下有3个节点，第三个节点下有两节点
main节点和第二个节点之间的连线有毛刺

**Comment by ssshooter** [comment]
![image](https://github.com/ssshooter/mind-elixir-core/assets/13051472/c66540de-a1f3-4e4c-87da-e186fc3d28d6)

这样？

**Comment by tigerxiongj** [comment]
对
