### ISSUE TITLE
为什么移除了nodeMenu?

### ISSUE THREAD

**Issue by Mikuu** [ssshooter/mind-elixir-core#184]
很漂亮的工具，但我看从2.0版本开始就移除了nodeMenu，能问一下为什么吗？感觉nodeMenu很实用呀？我现在用的2.0.2的版本，就没有nodeMenu了T_T

另外，文档里面的示例代码有一行.install(plugin)，但文档里面好像没有关于plugin的介绍，哪里能看到怎么用哪些plugin吗？

谢谢！

**Comment by Mikuu** [comment]
找到了

**Comment by ssshooter** [comment]
主要是因为移到组件更方便定制，不然靠传参很难满足所有人需求
