### ISSUE TITLE
最新的2.0版本，把节点菜单关闭后，无法再重新打开节点菜单了。

### ISSUE THREAD

**Issue by bluesaiz** [ssshooter/mind-elixir-core#186]
![image](https://github.com/ssshooter/mind-elixir-core/assets/40681310/22079638-9151-43a4-92ef-4f06a1f61a64)
老版本有缩小的图标：
![image](https://github.com/ssshooter/mind-elixir-core/assets/40681310/50b18be5-0709-443b-8ceb-37339fac985b)
新版本没了：
![image](https://github.com/ssshooter/mind-elixir-core/assets/40681310/53aeb7cc-e0ec-445b-88e2-ee9320c0cccc)
试用页面可以复现：
https://mind-elixir.com/#/

**Comment by ssshooter** [comment]
更新一下[node-menu](https://github.com/ssshooter/node-menu)就好了
