### ISSUE TITLE
修改Memo的时候没有触发listener

### ISSUE THREAD

**Issue by Mikuu** [ssshooter/mind-elixir-core#190]
大佬我又来了，好像是修改Memo的时候，无法触发listener，reshapeNode和edit的监听都没有被触发，修改font, tag, icon, url都能触发，但唯独修改Memo不行。

<img width="1791" alt="Screen Shot 2023-06-25 at 10 39 21 AM" src="https://github.com/ssshooter/mind-elixir-core/assets/11648253/a0fec67c-cc9c-4562-8771-c1d0b3152f9f">

**Comment by Mikuu** [comment]
Memo的数据添加、修改是生效的，就是没能触发listener，不方便添加响应事件 T_T

**Comment by ssshooter** [comment]
更新一下 [node-menu](https://github.com/ssshooter/node-menu)，v1.0.2 添加了 name 为 updateMemo 的 operation

**Comment by Mikuu** [comment]
给力！
