### ISSUE TITLE
直接回车创建new node没有触发finishEidt事件

### ISSUE THREAD

**Issue by Mikuu** [ssshooter/mind-elixir-core#192]
大佬我又来了，有个问题，操作步骤如下：
1. 点击根节点，敲击回车键，会生成**new node**，同时触发addChild和beginEdit事件，new node的topic处于选中待编辑状态；
2. 此时不做任何编辑，直接敲击回车键，能完成new node的创建，但没有触发finishEdit事件；

有没有办法在这种情况下也触发finishEdit事件，或以别的什么方式告知这个new node创建完成呢？

<img width="1792" alt="Screen Shot 2023-06-29 at 10 51 30 AM" src="https://github.com/ssshooter/mind-elixir-core/assets/11648253/2fb9b407-95f3-4da6-bea4-fae1232bda3d">

**Comment by ssshooter** [comment]
没有修改内容不触发 `finishEdit`
