### ISSUE TITLE
It would be great to allow drag and drop the child nodes anywhere in the map

### ISSUE THREAD

**Issue by mduvernon** [ssshooter/mind-elixir-core#205]
It would be great to allow drag and drop the child nodes
 - I can't move my child nodes where I want

**Comment by ssshooter** [comment]
You mean drag and detach from the map?

**Comment by fkloepper** [comment]
I think he means freely positioning the nodes. Currently they are all ordered automatically. 

In this example I repositioned node 2c freely. 
The rest of the nodes still have an organized layout. 
All nodes are still connected
![image](https://github.com/ssshooter/mind-elixir-core/assets/18051404/0e9a142e-5324-487f-ab18-ef2dfb70ec22)

**Comment by ssshooter** [comment]
> I think he means freely positioning the nodes. Currently they are all ordered automatically.
> 
> In this example using react-flow I repositioned node 2c freely. The rest of the nodes still have an organized layout. All nodes are still connected ![image](https://user-images.githubusercontent.com/18051404/254674235-0e9a142e-5324-487f-ab18-ef2dfb70ec22.png)

Based on the current code, it would be difficult to add this feature.
