### ISSUE TITLE
Can you help explain what a custom link is?

### ISSUE THREAD

**Issue by awweather** [ssshooter/mind-elixir-core#207]
I see in the source code linkDiv.ts, we have some logic for generating a custom link.

Can you explain how this is used?  Is this a feature we can take advantage of?  It looks as though it would allow us to tell mind elixir code to link two nodes together, but I'm not finding an example of how we'd supply this data.

On second thought, I did find linkData.  Is that what we would use?

Love your work!

**Comment by ssshooter** [comment]
![image](https://github.com/ssshooter/mind-elixir-core/assets/13051472/9c039620-6023-4b65-b074-16feea48dba1)
Use it by clicking `Link` then click another node

**Comment by awweather** [comment]
Thank you!
