### ISSUE TITLE
v0.11.0 cdn引入时报错：regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by xiweicheng** [ssshooter/mind-elixir-core#21]
![image](https://user-images.githubusercontent.com/9198971/93660066-de8f2300-fa7d-11ea-954f-1723b5369aeb.png)

**Comment by ssshooter** [comment]
版本更新后需要先引入 https://cdn.jsdelivr.net/npm/regenerator-runtime

**Comment by xiweicheng** [comment]
> 版本更新后需要先引入 https://cdn.jsdelivr.net/npm/regenerator-runtime

OK, thks.
