### ISSUE TITLE
is there way to change border color of 1st child same as connection color

### ISSUE THREAD

**Issue by asith-w** [SSShooter/mind-elixir-core#210]
border color of 1st child is currenly black . is there way to change it same as connection color ? 
![image](https://github.com/ssshooter/mind-elixir-core/assets/5784846/c0143518-13c0-4465-9e66-a29c3b4014bd)

**Comment by ssshooter** [comment]
Please wait for 3.0.0 update

**Comment by Mikuu** [comment]
Version: 3.2.1

The border color of the first node is still fixed, not align with the lines:
<img width="334" alt="Screen Shot 2023-10-02 at 11 09 19" src="https://github.com/ssshooter/mind-elixir-core/assets/11648253/d0616c08-8efe-47c6-be18-bd462b8e5a9d">

**Comment by ssshooter** [comment]
`branchColor` of a primary node should be explicitly set.

> Version: 3.2.1
> 
> The border color of the first node is still fixed, not align with the lines: <img alt="Screen Shot 2023-10-02 at 11 09 19" width="334" src="https://user-images.githubusercontent.com/11648253/271874919-d0616c08-8efe-47c6-be18-bd462b8e5a9d.png">

**Comment by asith-w** [comment]
this is done with  v4.0
