### ISSUE TITLE
detecting node menu status 

### ISSUE THREAD

**Issue by asith-w** [ssshooter/mind-elixir-core#212]
Is there a way to detect the status of the node menu, such as whether it is 'opened' or 'closed'? Alternatively, is there a method to close the node menu?

![image](https://github.com/ssshooter/mind-elixir-core/assets/5784846/4b2e1bb1-b0e7-48ab-9f60-aeb998cc95b5)

**Comment by ssshooter** [comment]
Node menu dosen't expose any interface. We highly recommand you customize your own node menu. https://github.com/ssshooter/node-menu
