### ISSUE TITLE
Restrict number of sub childs(depth)

### ISSUE THREAD

**Issue by asith-w** [ssshooter/mind-elixir-core#213]
Is there a method to prevent the   generation of new child nodes after a certain depth, such as in the hierarchy: root -> child-child -> child -> child-child?   
Alternatively, could users be restricted from creating new nodes by simply pressing and holding the 'tab' key? 
(This is because having too many child nodes can make the mind map look  confusing like this)
![image](https://github.com/ssshooter/mind-elixir-core/assets/5784846/404ba295-d2a9-4a88-bd59-e6e98ab76055)

**Comment by ssshooter** [comment]
Like this
```javascript
// ...
before: {
    insertSibling() {
      if(mei.currentNode.parent.children.length > 100)return false
      else return true
    },
}
// ...
```

**Comment by asith-w** [comment]
Thank you very much for the quick reply

**Comment by asith-w** [comment]
However, this it doesn't appear to function as expected. Is there a particular reason for this behavior? 
https://codesandbox.io/s/sleepy-volhard-x9p2nw

**Comment by ssshooter** [comment]
> > The version you use is too old, `before` is not supported.
> 
> it is same for the 2.0.10 . should i use version 3 ?

Use 3.0 if breaking changes don't affect you too much.
