### ISSUE TITLE
有办法获取节点的坐标位置吗

### ISSUE THREAD

**Issue by lcm1475** [ssshooter/mind-elixir-core#222]
希望能获取到节点的坐标位置
通过this.container.scrollTo方法定位到想要显示的节点

**Comment by ssshooter** [comment]
`scrollIntoView` 不可以？

**Comment by lcm1475** [comment]
请问应该如何使用啊 我看Topic对象才有scrollIntoView方法 如何获取或者拿到我想要的那个Topic啊

**Comment by lcm1475** [comment]
搞定了 没事了 谢谢
