### ISSUE TITLE
导出图片出错

### ISSUE THREAD

**Issue by lcm1475** [ssshooter/mind-elixir-core#223]
<img width="1382" alt="image" src="https://github.com/ssshooter/mind-elixir-core/assets/9637601/7bf64435-cc5b-4398-b415-55284a801c01">
显示这个错误

**Comment by ssshooter** [comment]
导出图片仅支持远古的 1.x

**Comment by lcm1475** [comment]
那现在有什么方法能导图图片和SVG吗 大佬

**Comment by lcm1475** [comment]
要按照这个文件夹改吗？https://github.com/ssshooter/export-image/blob/157b254d6861e838441f38302ff874cbc6b7b669/painter/index.js#L8

**Comment by ssshooter** [comment]
是的，思路不复杂，但是细节比较多

> 要按照这个文件夹改吗？https://github.com/ssshooter/export-image/blob/157b254d6861e838441f38302ff874cbc6b7b669/painter/index.js#L8

**Comment by lcm1475** [comment]
试了一下 一脸懵逼 能加个wx吗 大佬
