### ISSUE TITLE
Map is moving with cursor after open the menu

### ISSUE THREAD

**Issue by Mikuu** [ssshooter/mind-elixir-core#226]
Version: 3.2.1

Reproduce:
1. right click on a node to open the menu,
2. do nothing but click outside of the menu to close the menu,
3. [Actual Result] the map is linking to the cursor, move cursor moving the map together.
4. [Expect Result] after close the menu, cursor need move free without moving the map.

**Comment by ssshooter** [comment]
https://codepen.io/ssshooter/pen/OJrJowN

Can not reproduce the situation you describe

**Comment by Mikuu** [comment]
Like this:
https://github.com/ssshooter/mind-elixir-core/assets/11648253/82abcbb4-d18e-492e-96db-f3046cece14e

You can see the map is moving together with the cursor.
Also, this is happening on my Macbook when operating on the trackpad.
