### ISSUE TITLE
Support move map diagonally

### ISSUE THREAD

**Issue by Mikuu** [ssshooter/mind-elixir-core#227]
Version: 3.2.1

Description:
The current map can only move vertically and horizontally, it would be nice to support move diagonally. ^_^

**Comment by ssshooter** [comment]
Do you mean ... this?

https://github.com/ssshooter/mind-elixir-core/assets/13051472/ba50bca3-5473-44f6-a9d6-3d9cca21c302

**Comment by Mikuu** [comment]
Yes, that's what I mean exactly, but what I have is like this:

https://github.com/ssshooter/mind-elixir-core/assets/11648253/e57e6a4c-a3fb-4066-83c0-9f22f7cd3627

this is the behavior on Macbook moving with trackpad, can only go vertically and horizontally.

**Comment by ssshooter** [comment]
It's a default scroll behavior browser provide, and it can be dragged diagonally with my touch pad (windows) if you initially drag diagonally
