### ISSUE TITLE
Root node editing area

### ISSUE THREAD

**Issue by asith-w** [ssshooter/mind-elixir-core#228]
When editing the root node, the text editing area shifts to the left side. Is this intentional?

https://codesandbox.io/s/mind-elixir-3-x-react-18-x-vy9fcq?file=/Hello.js

![image](https://github.com/ssshooter/mind-elixir-core/assets/5784846/d4b46339-5c1c-498b-93c9-15d6364e8fdc)

**Comment by ssshooter** [comment]
It should be fixed in the latest version.
