### ISSUE TITLE
foreignObject Breaking svg2pdf.js PDF Generation

### ISSUE THREAD

**Issue by phyng** [ssshooter/mind-elixir-core#230]
I've been using mind-elixir and recently started to generate PDFs using svg2pdf.js. However, I've run into an issue where `foreignObject` is not supported by [svg2pdf.js](https://github.com/yWorks/svg2pdf.js/issues/15), resulting in missing text in the generated PDFs.

I've attempted to apply the following patch, which seems to mitigate the issue:

```ts
const foreignObjects = svgElement.querySelectorAll('foreignObject')

foreignObjects.forEach((foreignObject) => {
  const text = document.createElementNS('http://www.w3.org/2000/svg', 'text')
  const childDiv = foreignObject.querySelector('div')!
  text.setAttribute('x', foreignObject.getAttribute('x')!)
  text.setAttribute('y', String(parseInt(foreignObject.getAttribute('y')!) + parseInt(childDiv.style.fontSize)))
  text.setAttribute('font-family', 'Noto Sans CJK SC')
  text.setAttribute('font-size', childDiv.style.fontSize)
  text.setAttribute('fill', childDiv.style.color)
  text.setAttribute('text-anchor', 'start')
  text.textContent = foreignObject.textContent!.trim()
  console.log(text.textContent, childDiv.style.color)
  foreignObject.parentNode!.replaceChild(text, foreignObject)
})
```

I've also looked at the source code and I'm curious as to why `generateSvgText` isn't used universally. If there's a way to either use `text` directly or enable it through an option, it would resolve my issue without needing the patch.

Any insights or assistance would be greatly appreciated.

**Comment by ssshooter** [comment]
> I'm curious as to why `generateSvgText` isn't used universally.

Because svg text doesn't wrap by default. You have to calculate width of each character to decide when to wrap a line, which is difficult and slow.

So If you don't care about text wrapping, you can just replace `generateSvgTextUsingForeignObject` with `generateSvgText`. 😂

**Comment by phyng** [comment]
I understand, for now, I'll use this patch. It works reasonably well in my current scenario, as the node text isn't extensive. If possible, could you add an option or another method that doesn't require modifying the mind-elixir source code? I anticipate that this patch could become unstable with future mind-elixir updates.

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/3a7271d026e64e53a3841d77c24e36d30456bfd3/api/mind-elixir.api.md?plain=1#L29

Have a try~

**Comment by phyng** [comment]
@ssshooter Thanks! It works! 

But https://github.com/ssshooter/mind-elixir-core/commit/4dddb324c03dba9791b08f97a28181b0a460050f#diff-22661bb30bb26ab73ab4ec6375682479d6635ce978aaa6b8a3f2ae02e68a9db0R50-R56 breaking another things:

When calling the `exportSvg()` or `exportSvg(true)`, an error message appears in the console: `Error: <rect> attribute width: Expected length, "auto".`

Upon checking, it appears that `<rect>` elements are being generated as `<rect x="661" y="821" rx="0px" ry="0px" width="auto" height="auto">`

This issue seems to arise because the `getComputedStyle` function, when used on a `span` element, returns a width value of `auto`.

**Comment by phyng** [comment]
> > @ssshooter Thanks! It works!
> > But [4dddb32#diff-22661bb30bb26ab73ab4ec6375682479d6635ce978aaa6b8a3f2ae02e68a9db0R50-R56](https://github.com/ssshooter/mind-elixir-core/commit/4dddb324c03dba9791b08f97a28181b0a460050f#diff-22661bb30bb26ab73ab4ec6375682479d6635ce978aaa6b8a3f2ae02e68a9db0R50-R56) breaking another things:
> > When calling the `exportSvg()` or `exportSvg(true)`, an error message appears in the console: `Error: <rect> attribute width: Expected length, "auto".`
> > Upon checking, it appears that `<rect>` elements are being generated as `<rect x="661" y="821" rx="0px" ry="0px" width="auto" height="auto">`
> > This issue seems to arise because the `getComputedStyle` function, when used on a `span` element, returns a width value of `auto`.
> 
> please check 3.2.6

Test successful, the functionality is now working as expected.
