### ISSUE TITLE
How to enable icons and hyperlinks in the context menu?

### ISSUE THREAD

**Issue by leolux** [SSShooter/mind-elixir-core#237]
![grafik](https://github.com/SSShooter/mind-elixir-core/assets/5385814/7a8f1370-d32e-4548-84cb-f194a230aa00)
In v3.0.2 there is no menu entry for icons or hyperlinks. How to configure the menu properly?

**Comment by SSShooter** [comment]
Use this https://github.com/ssshooter/node-menu
