### ISSUE TITLE
nextjs 中图标不显示

### ISSUE THREAD

**Issue by controZheng** [SSShooter/mind-elixir-core#238]
最新的Google浏览器
nextjs： 13
react：18
在nextjs中操作图标不显示，并且无法拖拽 
<img width="1166" alt="image" src="https://github.com/SSShooter/mind-elixir-core/assets/42229960/d7168744-ed17-4743-9afb-052796d2cf02">

<img width="862" alt="image" src="https://github.com/SSShooter/mind-elixir-core/assets/42229960/7c10e53b-1aff-4204-ae98-14b71c2083e8">

<img width="754" alt="image" src="https://github.com/SSShooter/mind-elixir-core/assets/42229960/1e8e5d4c-c77e-4fe7-8467-e2a9c920f372">

**Comment by SSShooter** [comment]
请提供最小复现
