### ISSUE TITLE
Download mindmap as image

### ISSUE THREAD

**Issue by asith-w** [SSShooter/mind-elixir-core#241]
Mindmap image can be downloaded using **exportPng** [method](https://github.com/SSShooter/mind-elixir-core?tab=readme-ov-file#export-as-a-image), but it has a styles issue.  
Is there a workaround to fix this problem ?

https://codesandbox.io/p/sandbox/mind-elixir-3-x-react-18-x-forked-jjzs6z

![filename (1)](https://github.com/SSShooter/mind-elixir-core/assets/5784846/6bc3e7d8-d952-40fb-a259-599fcc169084)

**Comment by SSShooter** [comment]
I find the cause of the problem. `getComputedStyle` returns a wrong result, but I can't reproduce it in local dev env.
See: https://codesandbox.io/p/sandbox/mind-elixir-export-image-bug-qxsmnj?file=%2FexportImage.ts%3A113%2C20-113%2C36
Maybe you can use `clientWidth` instead for now.

**Comment by SSShooter** [comment]
> Mindmap image can be downloaded using **exportPng** [method](https://github.com/SSShooter/mind-elixir-core?tab=readme-ov-file#export-as-a-image), but it has a styles issue. Is there a workaround to fix this problem ?
> 
> https://codesandbox.io/p/sandbox/mind-elixir-3-x-react-18-x-forked-jjzs6z
> 
> ![filename (1)](https://private-user-images.githubusercontent.com/5784846/297332038-6bc3e7d8-d952-40fb-a259-599fcc169084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDE4MTYsIm5iZiI6MTcwNTU0MTUxNiwicGF0aCI6Ii81Nzg0ODQ2LzI5NzMzMjAzOC02YmMzZTdkOC1kOTUyLTQwZmItYTI1OS01OTlmY2MxNjkwODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDEzMTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBjNDcxNGIwY2Q0MjEwZDMyMzhiYjViMWUzYTFiN2I0MzI0YTBkYmI1YTJiZTk1NTI2ZTBiZTYxODZhYWEzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CCLluSPSNhuRAus2ltbA0vwTzG92rWNJuBaFvTyKZlk)

Adding `*{box-sizing: border-box;}` can solve the problem.
