### ISSUE TITLE
I had a bug when using the api for the new sibling node；(我在使用添加兄弟节点api时发现一个缺陷)

### ISSUE THREAD

**Issue by xinFengQi** [SSShooter/mind-elixir-core#257]
When I add a sibling to the first child under the root node; I used a custom NodeObj, but the custom NodeObj doesn't actually work; Look at the source code and find this paragraph in the insertSibling function:

if (((h = s.parent) == null ?  void 0 : h.root) === ! 0 && ((u = (a = s.parent) == null ?  void 0 : a.children) == null ?  void 0 : u.length) === 1) {
this.addChild(C(s.parent.id));
return;
}
It feels like there are some problems; If repaired as
if (((h = s.parent) == null ?  void 0 : h.root) === ! 0 && ((u = (a = s.parent) == null ?  void 0 : a.children) == null ?  void 0 : u.length) === 1) {
this.addChild( n || C(s.parent.id));
return;
}

Better or not？

中文版======================================
当我为根节点下的第一个子节点新增一个兄弟节点时；我使用了自定义的NodeObj，但是实际上自定义的NodeObj并没有生效；看源码发现insertSibling函数中的这段：

if (((h = s.parent) == null ? void 0 : h.root) === !0 && ((u = (a = s.parent) == null ? void 0 : a.children) == null ? void 0 : u.length) === 1) {
this.addChild(C(s.parent.id));
return;
}
感觉存在一些问题；如果修复为
if (((h = s.parent) == null ? void 0 : h.root) === !0 && ((u = (a = s.parent) == null ? void 0 : a.children) == null ? void 0 : u.length) === 1) {
this.addChild( n || C(s.parent.id));
return;
}
是否更好？

**Comment by SSShooter** [comment]
Ok, it will be fixed soon 😯
