### ISSUE TITLE
在vue2项目中导入MindElixir 报错（webpack）

### ISSUE THREAD

**Issue by Hiohk** [SSShooter/mind-elixir-core#268]
import MindElixir from "mind-elixir";
在vue2项目中导入MindElixir 报错（webpack），请问是什么原因？是我使用的方式不对吗？
<img width="585" alt="" src="https://github.com/user-attachments/assets/ceac5e9e-b196-46d1-b35d-f135ee7b7e79">

**Comment by SSShooter** [comment]
https://codesandbox.io/p/sandbox/mind-elixir-3-x-vue-2-x-5kdfjp?file=%2Fsrc%2FApp.vue

确实是这么引入，感觉是 webpack 配置的问题
