### ISSUE TITLE
Waiting for more detailed docs.

### ISSUE THREAD

**Issue by hahadaba** [SSShooter/mind-elixir-core#269]
**Is your feature request related to a problem? Please describe.**
Your work is great! I just moved from simple-mind-map which is also wonderful.
I have two requests.
1) Can you make a method to destroy the instance? I worry about memory leakage.
2) Can you make more details for docs?
When I read the docs for example locale of options:
export type Options = {
    el: string | HTMLElement;
    direction?: number;
    locale?: string;
    draggable?: boolean;
    editable?: boolean;
    contextMenu?: boolean;
    contextMenuOption?: any;
    toolBar?: boolean;
    keypress?: boolean;
    mouseSelectionButton?: 0 | 2;
    before?: Before;
    newTopicName?: string;
    allowUndo?: boolean;
    overflowHidden?: boolean;
    generateMainBranch?: (this: MindElixirInstance, params: MainLineParams) => PathString;
    generateSubBranch?: (this: MindElixirInstance, params: SubLineParams) => PathString;
    mobileMenu?: boolean;
    theme?: Theme;
    nodeMenu?: boolean;
};
How many locale options should I use? And so on.

Respect!!!

**Comment by SSShooter** [comment]
1. There’s no destroy method for now, but I’ll add it in the future.
2. `type Locale = 'cn' | 'zh_CN' | 'zh_TW' | 'en' | 'ru' | 'ja' | 'pt' | 'it' | 'es'`
