### ISSUE TITLE
can i set the position of the instance?

### ISSUE THREAD

**Issue by hahadaba** [SSShooter/mind-elixir-core#270]
**Is your feature request related to a problem? Please describe.**
when an instance is rendered, it always locates at the center.
I woud like it to align to left-center of the canvas.
![{C173C90D-DB4F-465E-A2C5-8243935E3909}](https://github.com/user-attachments/assets/c26688a7-1d32-4711-8c1a-eb8d49327d17)

**Describe the solution you'd like**
Add a _position_ property to initial options, eg: center-center,  left-center, right-center, maybe you have better names.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by SSShooter** [comment]
You can adjust it by referring to the `toCenter` function. 

https://github.com/SSShooter/mind-elixir-core/blob/caaf3b39bf2d231a4aca585d1dfe0b2f7a33a8d4/src/interact.ts#L175

**Comment by hahadaba** [comment]
thank you !
I got what I want with below codes:
const { container } = instance // instance = new MindElixir({...})
const offsetX  = 100 // offset to the left side as you want
container.scrollTo(10000 - offsetX, 10000 - container.offsetHeight / 2)

thank you very much!
