### ISSUE TITLE
当我在me-parent节点下想添加节点时，会导致添加的节点坐标发生错误

### ISSUE THREAD

**Issue by JasionM** [SSShooter/mind-elixir-core#278]
![image](https://github.com/user-attachments/assets/472ac483-065c-45de-9799-e6e26b816a4a)

这块代码是通过children下标方式直接获取，导致出现了问题，expander是固定用 me-epd 名称，应该用节点名称过滤查询才对吧

**Comment by SSShooter** [comment]
确实是可以通过dom操作手动插节点，但是非常麻烦，因为topic的结构其实是被包裹的，下面这一整组才是完整的topic结构
![image](https://github.com/user-attachments/assets/42f7c4bd-de6d-43f5-a097-b5611196a013)

所以还是不建议用dom操作插入😂

**Comment by JasionM** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JasionM** [comment]
主要是也没有别的方式可以插入自定义节点，而且你们源码中是用children的下标拿的expander，这个操作逻辑也不太合理，除非说以后这里的结构是固定的了？

**Comment by SSShooter** [comment]
https://github.com/SSShooter/mind-elixir-core/blob/67909b06e4dcd059fa89c6737815b18712600178/src/types/dom.ts#L16
确实是固定的

**Comment by JasionM** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
