### ISSUE TITLE
请问是否有只读模式和编辑模式之间切换的功能？

### ISSUE THREAD

**Issue by wjw020206** [SSShooter/mind-elixir-core#281]
非常感谢您的付出，不知道是否有只读模式和编辑模式之间切换的方法？

**Comment by SSShooter** [comment]
直接把实例的  `editable` 设为 `false` 就可以了

**Comment by wjw020206** [comment]
> 直接把实例的 `editable` 设为 `false` 就可以了

好的，非常感谢
