### ISSUE TITLE
how to get the "change" event?

### ISSUE THREAD

**Issue by hahadaba** [SSShooter/mind-elixir-core#282]
**Is your feature request related to a problem? Please describe.**
首先感谢老大的伟大作品。有个问题项请教：能否实现一个类似表单项的change或者input事件监听？我的需求是，用户对脑图做了任何增删改的操作，我就调用保存接口保存数据。
先谢谢了！

**Comment by SSShooter** [comment]
https://github.com/SSShooter/mind-elixir-core?tab=readme-ov-file#event-handling

listen `operation` 就可以了

**Comment by hahadaba** [comment]
已实现！谢谢老大！
