### ISSUE TITLE
Help for node-specific  context menu

### ISSUE THREAD

**Issue by daniele-paltrinieri-79** [SSShooter/mind-elixir-core#287]
**Is your feature request related to a problem? Please describe.**
Possibility to have context menu with totally different operation for the various node

**Describe the solution you'd like**
Possibility to set custom context menu directly on the node object

**Additional context**
I would like to use the library inside a project where the mind-map must be readonly (no operation related to the map itself, ex: adding/removing node, etc..). Each node can represent a different type of item. Using the context menu, I want to allow the user to perform operations on the object which is represented by the item. Clicking on the voice on the context menu I want to open a modal or redirecting the user to a page where He/she can perform the operation.
I have checked the contextMenu plugin where based on the fact that the node is root or not, the voices are enable or disable. Can I  obtain totally different voices of the menu for each node using a similar implementation?

**Comment by SSShooter** [comment]
You can customize the context memu using the `extend` options.
https://github.com/SSShooter/mind-elixir-core/blob/01b95b044ca9605743e0dc17412e22514af8e9e6/src/dev.ts#L37
You can also disable the build-in context menu and write your own menu with your UI components.

**Comment by daniele-paltrinieri-79** [comment]
Hi, I have checked the extend options but, if I have understood well, the
options apply to all the nodes of the map. What I need is to apply
different options to different nodes of the map (ex node1: option 1 and 2,
node2: option 3 and 4 and so on). Is it possible to obtain this using the
extend options?

**Comment by SSShooter** [comment]
You’re correct—the extend options apply to all nodes. To customize options per node, you’ll need to create your own context menu, or you can modify the built-in one as a starting point.

**Comment by daniele-paltrinieri-79** [comment]
Ok, thanks.

**Comment by daniele-paltrinieri-79** [comment]
Hi, I was able to create a custom plugin to generate the context menu with my necessity. So, I close the issues since for me is done.
