### ISSUE TITLE
How to init new mind map along with previous?

### ISSUE THREAD

**Issue by Nehasoni988** [ssshooter/mind-elixir-core#30]
I have initialized one mind map by following the code of the repo, now I want to initialize another mind map bu it throws the error- "**Cannot read property 'className' of null at me.init**".

My source code is-

// vue file
 ```
<v-btn color="primary" @click="initializeSecond()">Add one more mind map</v-btn>
 <v-row no-gutters>
        <v-col sm="6">
          <div id="map-1" style="width: 100%; height: 500px"></div>
        </v-col>
        <v-col sm="6">
          <div id="map-2" style="width: 100%; height: 500px"></div>
        </v-col>
 </v-row>
```

// Js code
```
import MindElixir, { E } from "mind-elixir";

data() {
    return {
    ME: null,
    ME_1: null   
 }
},

mounted() {
  let options = {
    el: '#map-1',
    direction: MindElixir.LEFT,
    // the data return from `.getAllData()`
    data: dummyData,
    draggable: true, // default true
    contextMenu: true, // default true
    toolBar: true, // default true
    nodeMenu: true, // default true
    keypress: true, // default true
    locale: 'en', // [zh_CN,zh_TW,en,ja] waiting for PRs
    overflowHidden: false, // default false
    primaryLinkStyle: 2, // [1,2] default 1
    primaryNodeVerticalGap: 15, // default 25
    primaryNodeHorizontalGap: 15, // default 65
    contextMenuOption: {
      focus: true,
      link: true,
      extend: [
        {
          name: 'Node edit',
          onclick: () => {
            alert('extend menu')
          },
        },
      ],
    },
    allowUndo: false
  }

  this.ME = new MindElixir(options);
  this.ME.init();
},

methods: {
    async initializeSecond() {
      try {
      let option = {
        el: '#map-2',
        direction: MindElixir.LEFT,
        // the data return from `.getAllData()`
        data: dummyData,
        draggable: true, // default true
        contextMenu: true, // default true
        toolBar: true, // default true
        nodeMenu: true, // default true
        keypress: true, // default true
        locale: 'en', // [zh_CN,zh_TW,en,ja] waiting for PRs
        overflowHidden: false, // default false
        primaryLinkStyle: 2, // [1,2] default 1
        primaryNodeVerticalGap: 15, // default 25
        primaryNodeHorizontalGap: 15, // default 65
        contextMenuOption: {
          focus: true,
          link: true,
          extend: [
            {
              name: 'Node edit',
              onclick: () => {
                alert('extend menu')
              },
            },
          ],
        },
        allowUndo: false
      }
      this.ME_1 = await new MindElixir(option);
      this.ME_1.init();
      } catch (error) {
        console.error('______', error)
      }
    }
}
```

// Error

![Screenshot from 2021-01-18 12-00-32](https://user-images.githubusercontent.com/33506558/104879970-d4762600-5984-11eb-8196-54603ea73b1e.png)

Could you please help? @ssshooter

**Comment by ssshooter** [comment]
Which version do you use?

**Comment by Nehasoni988** [comment]
> Which version do you use?

"mind-elixir": "^0.13.3",

**Comment by ssshooter** [comment]
I try to render two maps with vue and it seems working.

https://codesandbox.io/s/mind-elixir-vue-forked-jl5v6?file=/src/App.vue

Could you reproduce the problem in codesandbox.io?

**Comment by Nehasoni988** [comment]
I have copy-pasted your code and it is working, I didn't found any difference, now this error has resolved.
But, I run your code of sandbox, when I am changing the color of the ME2 map, it is changing the color of the ME map,
could you please look into it?

**Comment by ssshooter** [comment]
what's "change color" means?

**Comment by Nehasoni988** [comment]
I have recorded the behavior, please have a look. 
I am changing the background color and font color of the second map but the first map's colors are changing.

https://www.awesomescreenshot.com/video/2416575?key=8cc66692123760e54b91c4f090ceca5e

**Comment by ssshooter** [comment]
ok, it's a bug 😂

**Comment by Nehasoni988** [comment]
> ok, it's a bug

:-D

Okay, please update me after fixing this, I have an urgent deadline.
Thanks!

**Comment by ssshooter** [comment]
Fixed it, please update to 0.13.4 :-D

**Comment by Nehasoni988** [comment]
> Fixed it, please update to 0.13.4 :-D

Hey, I have upgraded the version, it is throwing another error.
Please have a look

https://codesandbox.io/s/xenodochial-mclaren-xmh51?file=/src/App.vue

@ssshooter

**Comment by ssshooter** [comment]
0.13.5 fixed 😂

**Comment by Nehasoni988** [comment]
😅
Thanks a bunch!
Everything is working now. Giving star ⭐

**Comment by Nehasoni988** [comment]
Hey,
One more thing I need to ask, Whenever I am adding new mind map, I am passing data like-
```
let exampleData = {
          nodeData: {
            id: uuidv4(),
            topic: 'new topic',
            root: true,
            children: [],
            parent: null
          },
          linkData: {}
        };
```

This is working fine for first time, but when I reload the page, and trying to add mind map again, this is showing error like this-

![Screenshot from 2021-01-19 15-09-18](https://user-images.githubusercontent.com/33506558/105016442-a5d17b80-5a68-11eb-9e4c-8f1f320a41c9.png)

Do you have any idea?

@ssshooter

**Comment by ssshooter** [comment]
Reproduction Needed 😥

**Comment by Nehasoni988** [comment]
> Reproduction Needed

Sorry, but I can't reproduce the problem because I have a lot more code also I am using vuex router and all kinds of stuff, let me elaborate on the problem in another manner.

I have seen in the repository's example data that the nodeData object is not having any parent property.
Now, what my workflow is-

1. I have a button on which click I generate a new map data using MindElixir.new("Root Node").
2. I have a save button on which click I get the data of just created map using map.getAllData() and save this data in my database and on component's mounted hook I retrieve the data from the database (which I just stored) and pass it to the map initialization property like this-
    1. let options = {data: database_retrieved_data}; 
    2. let var_name = new MindElixir(options); 
    3. var_name.init();
Everything is working fine till here.

Now when I add some child nodes to any map and click on the save button (which will take the data using the map.getAllData()) and send this data to Database for saving purpose, and also store this data into my state. It is throwing an error-

![Screenshot from 2021-01-20 11-14-59](https://user-images.githubusercontent.com/33506558/105132492-03210780-5b11-11eb-875f-b1991d59b9eb.png)

Also, after adding child nodes to some existing map, when I click on the button "create_map" it is also throwing the same problem.

I don't understand but I have seen that whenever I retrieve the data from DB, I found that nodeData object has parent property which has the value undefined, I have tried to remove the parent property from nodeData (as error is saying about parent property) but the property is not removing at all.

Please, Let me know if any further explanation needed.
Thanks!

**Comment by ssshooter** [comment]
I consider the problem occurs because of the `getAllData` function.

```javascript
let getAllData = function () {
  let data = {
    nodeData: this.nodeData,
    linkData: this.linkData,
  }
  return JSON.parse(
    JSON.stringify(data, (k, v) => {
      if (k === 'parent') return undefined
      if (k === 'from') return v.nodeObj.id
      if (k === 'to') return v.nodeObj.id
      return v
    })
  )
}
```

Check if your data contain any object that `JSON.stringify`  can't process.

**Comment by Nehasoni988** [comment]
the getAllData function is returning the data like this-

![Screenshot from 2021-01-20 11-39-24](https://user-images.githubusercontent.com/33506558/105134696-d111a480-5b14-11eb-9602-68a0bc9224b1.png)


which has no parent property, and the same data I am storing in the DB. but on mounted when I retrieve this same data from DB and passing it to the initialization object, somehow it is adding the parent property to the nodeData, like that-

![Screenshot from 2021-01-20 11-41-19](https://user-images.githubusercontent.com/33506558/105134705-d40c9500-5b14-11eb-8b08-7177d18f5b93.png)

I can understand it's hard to debug without looking into the code, If it's still unclear to you, let me know, I will upload the sample project on git you can clone and test this.

**Comment by ssshooter** [comment]
So the `getAllData` function is not the one throwing error? 😂

**Comment by Nehasoni988** [comment]
:-D

I don't know which is causing the error, I am creating the repository and uploading it.
I'll inform you, please clone it and help me to figure out the problem.
I am so close to my integration of this package into my project, it would be a great help if this single issue will get resolved.

**Comment by Nehasoni988** [comment]
Hey, I found when this error occurs, just follow these steps-

1. Copy example data from here https://github.com/ssshooter/mind-elixir-core/blob/develop/src/exampleData/1.js, store this data in the Vue state.
2. Now in component, take the data from state and pass in configurations' data key, check if the mind map has generated for this data.
3. If generated then reload the page, the error will come.

**Comment by Nehasoni988** [comment]
See this video,

[https://www.awesomescreenshot.com/video/2444909?key=47f1d9de50c40894d84aef2181f1d62e](url)




When I click on the green button, I export the data by calling the getAllData function like map.getAllData. map is the variable which I used to store when init the map and its auto update when I call export data.

It seems that there is a problem with getAllData function, because its structure is like-

```
parent: {
    children: [
        parent: {
            children: [
            ]    
      }
]
```

@ssshooter

**Comment by ssshooter** [comment]
```
parent: {
    children: [
        parent: {
            children: [
            ]    
      }
]
```
this structure should not cause error.
```
JSON.stringify(data, (k, v) => {
      if (k === 'parent') return undefined
      if (k === 'from') return v.nodeObj.id
      if (k === 'to') return v.nodeObj.id
      return v
    })
```
this part of code had skipped the `stringify` of parent propertys.

**Comment by Nehasoni988** [comment]
Do you have any idea what I am doing wrong or why I am getting this kind of data structure?
I do need to save the modified data to the database, instead of getAllData what else I can use to export data?

@ssshooter

**Comment by ssshooter** [comment]
I think you can directly access meObject.nodeData and do whatever you want to

**Comment by Nehasoni988** [comment]
> I think you can directly access meObject.nodeData and do whatever you want to

Hey, I did this, it Is producing the same error.
Just check this please - https://codesandbox.io/s/mind-elixir-vue-forked-xxm79?file=/src/App.vue

and add any child node, and click on the export data button, you should see something like that- children->parent->children->...


![Screenshot from 2021-01-21 10-19-28](https://user-images.githubusercontent.com/33506558/105281535-6757d000-5bd2-11eb-9cf8-34e46f3385d8.png)


@ssshooter

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/105282660-cecd4a00-5be9-11eb-8320-0bd840e517dd.png)

https://codesandbox.io/s/mind-elixir-vue-forked-7bphn

`nodeData` has `parent` property when you directly access it, but it doesn't means `getAllData` will throw an error.

**Comment by Nehasoni988** [comment]
No, getAllData is not throwing the error, but it seems that after calling getAllData on ME object, it is assigning something to ME's nodedata that's why the me's nodedata is having a circular json structure, please look at this-

https://codesandbox.io/s/mind-elixir-vue-forked-oxjr2?file=/src/App.vue

(See the last console message nodeData property.)

(It's my row thought, pardon for saying wrong) 
when ME's nodeData get updates after calling getAllData, ME object updates with circular structure and ME object is in a variable so this variable is not having a correct value and we can't pass this data for mind map initialization.

**Comment by ssshooter** [comment]
As below source code shows, `getAllData` doesn't assign anything to `nodedata` 😂

```
let getAllData = function () {
  let data = {
    nodeData: this.nodeData,
    linkData: this.linkData,
  }
  return JSON.parse(
    JSON.stringify(data, (k, v) => {
      if (k === 'parent') return undefined
      if (k === 'from') return v.nodeObj.id
      if (k === 'to') return v.nodeObj.id
      return v
    })
  )
}
```

**Comment by Nehasoni988** [comment]
There is no way to export the data of a map and store it somewhere.

 😓

**Comment by ssshooter** [comment]
How about trying to clone the `nodeData` manually?

**Comment by Nehasoni988** [comment]
Yes, I need to handle it manually.

**Comment by Nehasoni988** [comment]
Hey, could you please tell me where is the init function? I searched in the DOC but didn't found it.

Actually, I noticed that whenever change the direction either initLeft or initRight or initSide, map calls init() again, so the saved color also change back to default blue color again.

I want to debug this.

@ssshooter

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/8595747d73c3553b1f49377cd695f5c4f427dba9/src/index.js#L323

**Comment by Nehasoni988** [comment]
is there any way to listen when initLeft or initRight functions are being called?

@ssshooter

**Comment by ssshooter** [comment]
no way for now, but you can write your own `initRight` base on below code.

```
initRight = function () {
  this.direction = 1
  this.init()
  // do something else
}
```

**Comment by Nehasoni988** [comment]
Okay

**Comment by Nehasoni988** [comment]
Hey,

Don't tell me it does not support RTL  😟 😟 😟

**Comment by ssshooter** [comment]
😂 try to cover the original css with custom css

**Comment by Nehasoni988** [comment]
Yeah, this will burn my head :`(

**Comment by Nehasoni988** [comment]
Hey @ssshooter 

1. Change the color of the root node.
2. Change the position of the mind map, either left or right.
3. The color of the root node has been reset.

see this - https://www.awesomescreenshot.com/video/2527408?key=e0996b3600ac69156f0217ccd379d632

Is there any way I can fix this?

**Comment by ssshooter** [comment]
I had uploaded the dev branch and you can take it as  referance.

**Comment by Nehasoni988** [comment]
Hey,

The toolbar options and node menu is hiding in full-screen mode only mind map is visible, can you please tell me how to fix this?

@ssshooter

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/9cc25786cfce23db22f49a2a198b12f551632f4f/src/plugin/toolBar.js#L25

Change this line to `mind.container.parentElement.requestFullscreen()`

**Comment by Nehasoni988** [comment]
Yeah, I tried the same logic, a bit different-

```
fc.onclick = () => {
    // when full screen mode is on, change the bg color;
    mind.mindElixirBox.style.background = "#fff";

    // Make element in full screen mode
    mind.mindElixirBox.requestFullscreen()
  }

```

Thanks for letting me know.
:-D

**Comment by Nehasoni988** [comment]
Hey,

The calculation in linkdiv.js is having too large code 😅, how can I customize the CSS for RTL support?
Can you please suggest?

@ssshooter

**Comment by ssshooter** [comment]
I'am not familiar with `direction` property, directly adding `direction:rtl` to tpc element may work ? 😂

**Comment by Nehasoni988** [comment]
I want to customize the package language and I have the locale "heb" (Hebrew) which is RTL.
So when my APP is in RTL mode the map's nodes disappear.

Can you have a look at it, when I change the direction of the map-container (Which is exactly when my APP is in RTL mode), what happened to it?

https://codesandbox.io/s/mind-elixir-vue-forked-csebo?file=/src/App.vue

**Comment by ssshooter** [comment]
it's weird that nodes disappear 😂
have you inspected the element? nodes don't render correctly or there's a error thorwn?

**Comment by Nehasoni988** [comment]
I meant, As much as I have observed, the linkDiv.js is having the calculation of nodes always from a fixed direction, either left or right, and also, the package has not any locale which supports RTL, and that's why when I turned my application in RTL mode, the nodes become miscalculated and scattered at many places in the screen.

The above is my concern :`(

**Comment by ssshooter** [comment]
Could you provide a RTL environment for me to debug this issue?

**Comment by Nehasoni988** [comment]
Yeah sure, please follow this link-

https://codesandbox.io/s/mind-elixir-vue-forked-csebo?file=/src/App.vue

I have given the RTL direction to the .map-container which behaves exactly the same behavior when my Application is in RTL mode.
Any help from you would great.

**Comment by ssshooter** [comment]
```
.map-container {
  direction: ltr;
  tpc {
    direction: rtl;
  }
}
```
Take a try

**Comment by Nehasoni988** [comment]
When I should try this when the Application is in RTL mode?
Can you provide a demo at codepen?

**Comment by ssshooter** [comment]
https://codesandbox.io/s/mind-elixir-vue-forked-94j8l?file=/src/App.vue

**Comment by Nehasoni988** [comment]
Thanks, it worked!

**Comment by Nehasoni988** [comment]
Hello @ssshooter 

How did you manage the SVG files?

**Comment by ssshooter** [comment]
where and how do you use SVG?

**Comment by Nehasoni988** [comment]
I need to add an SVG of "heart" inside nodes, but I don't understand where I can put the SVG image in code and use it?
@ssshooter

**Comment by ssshooter** [comment]
you could modify codes here

https://github.com/ssshooter/mind-elixir-core/blob/9cc25786cfce23db22f49a2a198b12f551632f4f/src/utils/dom.js#L25

**Comment by ifunplus** [comment]
> > Reproduction Needed
> 
> Sorry, but I can't reproduce the problem because I have a lot more code also I am using vuex router and all kinds of stuff, let me elaborate on the problem in another manner.
> 
> I have seen in the repository's example data that the nodeData object is not having any parent property.
> Now, what my workflow is-
> 
> 1. I have a button on which click I generate a new map data using MindElixir.new("Root Node").
> 2. I have a save button on which click I get the data of just created map using map.getAllData() and save this data in my database and on component's mounted hook I retrieve the data from the database (which I just stored) and pass it to the map initialization property like this-
>    
>    1. let options = {data: database_retrieved_data};
>    2. let var_name = new MindElixir(options);
>    3. var_name.init();
>       Everything is working fine till here.
> 
> Now when I add some child nodes to any map and click on the save button (which will take the data using the map.getAllData()) and send this data to Database for saving purpose, and also store this data into my state. It is throwing an error-
> 
> ![Screenshot from 2021-01-20 11-14-59](https://user-images.githubusercontent.com/33506558/105132492-03210780-5b11-11eb-875f-b1991d59b9eb.png)
> 
> Also, after adding child nodes to some existing map, when I click on the button "create_map" it is also throwing the same problem.
> 
> I don't understand but I have seen that whenever I retrieve the data from DB, I found that nodeData object has parent property which has the value undefined, I have tried to remove the parent property from nodeData (as error is saying about parent property) but the property is not removing at all.
> 
> Please, Let me know if any further explanation needed.
> Thanks!
> 
> @ssshooter

for anyone who want to init mind map with saved data, you can use a deep copy of your saved data to init options->data. because the source code add parent link in mind.init(), that will change your origin data on account of objects in JavaScript are passed by reference.

**Comment by Nehasoni988** [comment]
Hello @ssshooter 

Can you please tell me which library you are using to link between nodes?
Do you use a library or do you do it own?

**Comment by ssshooter** [comment]
> Hello @ssshooter
> 
> Can you please tell me which library you are using to link between nodes? Do you use a library or do you do it own?

https://github.com/ssshooter/mind-elixir-core/blob/d5fdd9b5fe80c84528d27eb9c6371ebf1433efbe/src/linkDiv.ts#L22

**Comment by Nehasoni988** [comment]
Hello @ssshooter,

Can you please tell me what function is called when we drag the endpoints of a link (the red color link between nodes)?

![image](https://user-images.githubusercontent.com/33506558/173343204-ed4964cc-6ffd-45ee-a017-d401991389b1.png)

**Comment by ssshooter** [comment]
> Hello @ssshooter,
> 
> Can you please tell me what function is called when we drag the endpoints of a link (the red color link between nodes)?
> 
> ![image](https://user-images.githubusercontent.com/33506558/173343204-ed4964cc-6ffd-45ee-a017-d401991389b1.png)

https://github.com/ssshooter/mind-elixir-core/blob/2a497141d959879b626fff99c80ae86589f39109/src/utils/index.ts#L310

**Comment by Nehasoni988** [comment]
I want to add reference text on this link (For example there should be an ability to add text between nodes to know why those nodes are connected).
Can you help me to know if I can do this in code or do I have to make it on my own from scratch?

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/08c8b2cb47f4ae06f428e5c9a5542d090f84e146/src/customLink.ts#L67

Here is the position of the middle point of the link.

**Comment by Nehasoni988** [comment]
Hey, @ssshooter 

I need help understanding the image downloading process. 

Scenario 1- Inside this library's code, I have written image downloading code inside `toolbar.js` file like this, and it is working fine-

```
import { exportPng } from '../../painter'

 download_btn.onclick = () => {
    let map_container = mind
    map_container.scale((map_container.scaleVal = 1))
    setTimeout(async () => {
      exportPng(map_container, 'wer-smm')
    }, 1000)
  }
```

The same approach I am trying to use in my Vuejs project where I install this library and do code like this-

```
import painter from "mind-elixir/dist/painter";

let map_container = this.mind;
map_container.scale((map_container.scaleVal = 1));
setTimeout(async () => {
  painter.exportPng(map_container).then(async (res) => {});
}, 1000);
```

But this is not downloading the image correctly.

I am not sure which code I should provide you. Please let me know if you need further details.

**Comment by ssshooter** [comment]
> 

It throw an error? or just nothing happend?

**Comment by Nehasoni988** [comment]
It downloads the image but the image looks like this-

![Health  (1)](https://github.com/ssshooter/mind-elixir-core/assets/33506558/3e4850e5-ad5f-4aa0-a78b-aafcd13446d9)

But the correct image looks like this-

![wer-smm (11)](https://github.com/ssshooter/mind-elixir-core/assets/33506558/e3b55d5d-bea6-44e6-96c0-858dd1ceb2c4)

**Comment by ssshooter** [comment]
which version do you use?

**Comment by Nehasoni988** [comment]
0.16.3

**Comment by ssshooter** [comment]
Could you reproduce the bug on [https://codesandbox.io/](https://codesandbox.io)?
