### ISSUE TITLE
[Question] Control Scale/Fit?

### ISSUE THREAD

**Issue by logan-markewich** [ssshooter/mind-elixir-core#33]
I'm rendering the mindmap in a small div. 

Is there a way to control the zoom/scale/fit before it renders?

There's also some bugs in the toolbars when the parent div has height and width are set to 100%, I might just have to manually set some styling (it looks like the padding isn't calculated properly)

![image](https://user-images.githubusercontent.com/22285038/107089768-ccabe380-67c4-11eb-987f-df23126306a5.png)

**Comment by ssshooter** [comment]
For now, scale can only be changed after it renders 😥

**Comment by logan-markewich** [comment]
Maybe a future feature then! haha 

Thanks for the quick response 👍
