### ISSUE TITLE
默认Node下的子Node无法退出专注模式.

### ISSUE THREAD

**Issue by AkariMarisa** [ssshooter/mind-elixir-core#37]
我使用如下代码进行初始化, 其中data使用的是MindElixir.new方法创建一个默认的Topic.
```
import MindElixir, { E } from 'mind-elixir'

let options = {
  el: '#map',
  direction: MindElixir.LEFT,
  // create new map data
  data: MindElixir.new('new topic'),
  draggable: true, // default true
  contextMenu: true, // default true
  toolBar: true, // default true
  nodeMenu: true, // default true
  keypress: true, // default true
  locale: 'zh_CN', // [zh_CN,zh_TW,en,ja] waiting for PRs
  overflowHidden: false, // default false
  primaryLinkStyle: 2, // [1,2] default 1
  primaryNodeVerticalGap: 15, // default 25
  primaryNodeHorizontalGap: 15, // default 65
  allowUndo: false,
}

let mind = new MindElixir(options)
mind.init()
```
### 操作流程

当我在默认的Topic下创建子Node, 并且在子Node上打开右键菜单, 点击 **专注** , 此时是可以进入子Node的专注模式的. 但是这时候在进入专注模式的子Node上点击右键菜单的 **取消专注** , 此时无法退回到 **new topic** 这个默认根Node上.

**Comment by ssshooter** [comment]
是这么操作吗？

![b07f5487-09d7-42ca-9b73-17185be4f8a2](https://user-images.githubusercontent.com/13051472/111090880-21810d80-856c-11eb-96fc-8694a273b27a.gif)

**Comment by AkariMarisa** [comment]
是的, 我尝试用readme提供的[https://codepen.io/ssshooter/pen/GVQRYK](https://codepen.io/ssshooter/pen/GVQRYK)进行测试, 也是无法取消专注.

**Comment by ssshooter** [comment]
明白了，是一个bug
