### ISSUE TITLE
专注模式下两个问题

### ISSUE THREAD

**Issue by xiweicheng** [ssshooter/mind-elixir-core#38]
1、专注模式下getAllDataString()获取的content和专注前不一致，导致比较判断是否有新变更不准（明明没做任何变更）。
2、专注模式下getAllDataString()获取content保存后，下次加载编辑时对应专注节点无法再次进入专注模式了。

**Comment by xiweicheng** [comment]
是否可以考虑提供个判断mind是否存在变更的公开方法呢？

**Comment by ssshooter** [comment]
1 是一个 bug，已经修复了，试试更新版本有没有问题？

**Comment by xiweicheng** [comment]
> 1 是一个 bug，已经修复了，试试更新版本有没有问题？

看到develop分支没有什么更新，这边就是目前最新代码测试发现的问题。

**Comment by xiweicheng** [comment]
先前有个专注模式下的问题，也是这边发现上报的，看到有修复后，测试发现了上面的新问题。

**Comment by ssshooter** [comment]
> 是否可以考虑提供个判断mind是否存在变更的公开方法呢？

暂时可以用监听操作的方法判断数据有没有改变

```javascript
mind.bus.addListener('operation', operation => {
  isChanged = true
})
```
