### ISSUE TITLE
How to import markdown ?

### ISSUE THREAD

**Issue by Bapt5** [SSShooter/mind-elixir-core#44]
Hello I'm looking for create a mind map from a markdown file which was import. And I am searching How to support markdown with title and bullet and export markdown with title and bullet from the mind map? @ssshooter

**Comment by ssshooter** [comment]
For now, mind-elixir only support to export as markdown 😢
To import markdown file, maybe you could find a markdown to json lib to do this

**Comment by Bapt5** [comment]
Ok I will try to find a markdown to json. But do you know how to update the data of the mind map periodically? And how to export the markdown with title and bullet and not only with title ?

**Comment by ssshooter** [comment]
Update data:
```javascript
let newdata = {} // get new data
me.addParentLink(newdata) // add parent property in child nodes
me.nodeData = { /* new data */ } // set data to mind elixir
me.refresh() // re-paint mind map
```

modify `deep` to control when to show title or bullet:
https://github.com/ssshooter/mind-elixir-core/blob/79942a68b14c8875ab7d270b1ad25bfff351b04c/src/interact.js#L165
