### ISSUE TITLE
右键菜单优化定制化

### ISSUE THREAD

**Issue by alpschan** [ssshooter/mind-elixir-core#47]
是否考虑一下把右键菜单中的增加子节点、增加同级节点和删除节点都能定制化？

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/develop/src/plugin/contextMenu.js

复制一份右键插件自己定制再安装会更精准😂

**Comment by cactus1949** [comment]
您好，contextmenu.js这个文件我本地引入了，如何覆盖原来的😭，不太会搞了
