### ISSUE TITLE
Export Svg not rendered properly 

### ISSUE THREAD

**Issue by Kee-Ke** [ssshooter/mind-elixir-core#48]
I am storing the MindMap in a DB with getAllData() value, when i try to export from saved file, getting alignment issue
![hello (3)](https://user-images.githubusercontent.com/41342562/123598360-0b911300-d812-11eb-9660-f68656c45bb0.png)
![hello](https://user-images.githubusercontent.com/41342562/123598366-0df36d00-d812-11eb-8074-42770a2fd8b3.png)

**Comment by ssshooter** [comment]
Please update to 0.15.0 and try `exportSvg(instance, fileName)`

**Comment by ssshooter** [comment]
mind-elixir instance, such as `let mind = new MindElixir(options)`

**Comment by ssshooter** [comment]
`fileName` is the name of the file you want to exported, default value is the root topic.

**Comment by Kee-Ke** [comment]
@ssshooter  Thank you for your quick support , it is working fine

**Comment by Nehasoni988** [comment]
Hello @ssshooter 

I have forked the repository because I was needed some customization.

Now, I am exporting the image, I have done some modifications in the painter/index.js file because I am using CSS a bit differently but after downloading the image, the text is extracting from the box, see image. 

Can you please suggest how can I force the text to be inside the nodes, in the painter/index.js file?

![trial-41-](https://user-images.githubusercontent.com/33506558/132830944-aa6fa5f5-c641-4550-816c-0bc47a3c0686.png)

**Comment by ssshooter** [comment]
> Hello @ssshooter
> 
> I have forked the repository because I was needed some customization.
> 
> Now, I am exporting the image, I have done some modifications in the painter/index.js file because I am using CSS a bit differently but after downloading the image, the text is extracting from the box, see image.
> 
> Can you please suggest how can I force the text to be inside the nodes, in the painter/index.js file?
> 
> ![trial-41-](https://user-images.githubusercontent.com/33506558/132830944-aa6fa5f5-c641-4550-816c-0bc47a3c0686.png)

It's a known issue. svg text can't wrap automatically, so developer have to figure it out with a work-around 😭
and this problem is unsolved for now 😭

**Comment by Nehasoni988** [comment]
> > Hello @ssshooter
> > I have forked the repository because I was needed some customization.
> > Now, I am exporting the image, I have done some modifications in the painter/index.js file because I am using CSS a bit differently but after downloading the image, the text is extracting from the box, see image.
> > Can you please suggest how can I force the text to be inside the nodes, in the painter/index.js file?
> > ![trial-41-](https://user-images.githubusercontent.com/33506558/132830944-aa6fa5f5-c641-4550-816c-0bc47a3c0686.png)
> 
> It's a known issue. svg text can't wrap automatically, so developer have to figure it out with a work-around 
> and this problem is unsolved for now

:-(
No ideas?

**Comment by ssshooter** [comment]
solution 1: calculate width of every word and wrap them at a right place manually 😂
solution 2: svg foreign object

**Comment by Nehasoni988** [comment]
What does this foreign object do?

**Comment by ssshooter** [comment]
Something like embed html code in svg file.
https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/foreignObject

**Comment by Nehasoni988** [comment]
I have tried few CSS things, finally, I am able to handle text, but a new problem now, :-(

Can you tell me why these connected lines are so far from node-

![wer (12)](https://user-images.githubusercontent.com/33506558/133073065-5b3e66c6-4d69-4ee4-96e2-3999f88a96ae.png)

**Comment by Nehasoni988** [comment]
try this example data and export image, you will find the issue-

[https://gist.github.com/Nehasoni988/c3d84b11f3fa3ec62515619e505d9b8f](https://gist.github.com/Nehasoni988/c3d84b11f3fa3ec62515619e505d9b8f)

**Comment by ssshooter** [comment]
it seems position calculation goes wrong, need some time to repair this issue😵

**Comment by Nehasoni988** [comment]
> it seems position calculation goes wrong, need some time to repair this issue

Please inform me. I'll also try to fix this.

Thanks!

**Comment by ssshooter** [comment]
0.16.2 fixed

**Comment by Nehasoni988** [comment]
Thanks, it worked. 

:-)
