### ISSUE TITLE
能否给个结合Vue 2.0 以上版本使用的示例？

### ISSUE THREAD

**Issue by wwggyy** [ssshooter/mind-elixir-core#5]
能否给个结合Vue 2.0 以上版本使用的示例？谢谢。

**Comment by ssshooter** [comment]
script tag or single-file component?

**Comment by wwggyy** [comment]
> cript tag or single-file component?

Yeap

**Comment by ssshooter** [comment]
> > cript tag or single-file component?
> 
> Yeap

Both?

**Comment by wwggyy** [comment]
I have kown what to do, thank you.
