### ISSUE TITLE
vue.js中导出数据有案例吗？

### ISSUE THREAD

**Issue by 18252039750** [ssshooter/mind-elixir-core#55]

**Comment by ssshooter** [comment]
调用思维导图实例的 `getAllData()` 就行了，什么框架都可以

**Comment by 18252039750** [comment]
请问使用getAllData（）是将数据导出为后缀.js的文件吗？请问默认的保存路径是？

**Comment by ssshooter** [comment]
😂没有直接导出为文件的接口，要拿到数据之后自己保存为文件，通过 blob 和 a 标签之类的方法
