### ISSUE TITLE
Data import Gives [object object]

### ISSUE THREAD

**Issue by melvincarvalho** [ssshooter/mind-elixir-core#6]
```JavaScript
      console.log('d', d)
      let mind = new MindElixir({
        el: '#map',
        direction: MindElixir.LEFT,
        data: MindElixir.new(d), // can also set data return from .getAllData()
        draggable: true, // default true
        contextMenu: true, // default true
        toolBar: true, // default true
        nodeMenu: true, // default true
        keypress: true, // default true
      })
      mind.init()
```

Where d in console

```
linkData: Object {  }
nodeData: Object { id: "root", topic: "Solid Map", root: true, … }
```
![image](https://user-images.githubusercontent.com/65864/62486486-ba13b100-b7bf-11e9-8da9-8637ad23d27b.png)

Any ideas?

**Comment by melvincarvalho** [comment]
Looking here

https://github.com/ssshooter/mind-elixir-core/blob/master/src/index.js#L101

is should take the nodeData and linkData -- but they appear to be there

Not sure what is going wrong, I'll try and debug.

Thanks for a great app!

**Comment by melvincarvalho** [comment]
![image](https://user-images.githubusercontent.com/65864/62486797-78cfd100-b7c0-11e9-9369-c9c8fa2186ac.png)

**Comment by melvincarvalho** [comment]
Haha, got it!  No need for new MindElixir()

Can close!

**Comment by ssshooter** [comment]
😂hmmm, i should explain about this in doc
