### ISSUE TITLE
Support to join again with sub nodes ?

### ISSUE THREAD

**Issue by vkcorp** [ssshooter/mind-elixir-core#60]
Somebody(including me :)) think about joining the sub nodes again like below a linked issue :

https://community.miro.com/wish-list-32/mindmap-have-separate-nodes-join-into-1-node-at-end-see-image-1839

I guess it's not supported yet, do you have any plan to support it ?

**Comment by ssshooter** [comment]
it's hard to achieve this functionality due to the mechanism of mind-elixir 😥

**Comment by vkcorp** [comment]
I see and thanks for your answer !
