### ISSUE TITLE
Try to disable or block the editing anymore

### ISSUE THREAD

**Issue by vkcorp** [ssshooter/mind-elixir-core#62]
Hi, I have one more question while testing.
I want to disable editing and wanna see current work as final,
so tried to block it with disableEdit() like :

            mind.toCenter();
            mind.disableEdit();

But I still can add new child and set new color for my nodes.
Is there anyway to block to edit anymore ?

**Comment by ssshooter** [comment]
it's a bug, I will fix it 🤣

**Comment by vkcorp** [comment]
Oh I see ! Hope to be fixed soon :)

**Comment by ssshooter** [comment]
fixed ; )

**Comment by vkcorp** [comment]
Thanks alot for your help ! 
So I've tested it with 0.16.3, but I can still add new child after setting disableEdit().
I don't knwo what's wrong..

Downloaded it from : 
https://cdn.jsdelivr.net/npm/mind-elixir/dist/MindElixir.js

**Comment by vkcorp** [comment]
Ah, does the disableEdit() valid for only onkeydown and dbclick ?
How about items of contextmenu ? I tested with clicking a menu item of menu, "Add child".

**Comment by ssshooter** [comment]
🤣you are right, this is another fault.

**Comment by ssshooter** [comment]
0.16.4 fixed

**Comment by vkcorp** [comment]
Thanks 👍 , I will try again !
