### ISSUE TITLE
a line of each last node is pale or hidden 

### ISSUE THREAD

**Issue by vkcorp** [ssshooter/mind-elixir-core#63]
Hi, I found one more important issue while testing.

![image](https://user-images.githubusercontent.com/6039321/135963415-eee876f5-0f4f-436a-8f10-f353169c8101.png)

Each last line of nodes was pale or hidden, so I couldn't see it clearly.
I guess there is a line but overwrited by node object's outline.
Maybe we should increase the height of each node will solve it.

**Comment by ssshooter** [comment]
it's a known situation, but i don't have any solution for now.

**Comment by vkcorp** [comment]
Appreciates for your confirmation ! I will try to handle it if I can.

**Comment by vkcorp** [comment]
Ah could you point me out where is the code to draw the line ? Faster access for me ;)

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/08c8b2cb47f4ae06f428e5c9a5542d090f84e146/src/linkDiv.ts#L205
