### ISSUE TITLE
refresh is required after removing child (in context menu)

### ISSUE THREAD

**Issue by vkcorp** [ssshooter/mind-elixir-core#64]
After removing a child there was no update in my screen,
I guess I have to add refresh() at below code :

  remove_child.onclick = e => {
    if (isRoot) return
    mind.removeNode()
    **mind.refresh();**
    menuContainer.hidden = true
  }

**Comment by vkcorp** [comment]
Ah, I've checked it again accoring to your metion and found that
this issue can be reproduced at only Firefox browser (93.x in my case) !

**Comment by vkcorp** [comment]
I should use Chrome :)

**Comment by ssshooter** [comment]
> Ah, I've checked it again accoring to your metion and found that this issue can be reproduced at only Firefox browser (93.x in my case) !

do you have any error information using firefox?
