### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by wuxiaobin1995** [ssshooter/mind-elixir-core#67]
![image](https://user-images.githubusercontent.com/36044379/140243237-2b1dd7dc-6fbd-411e-8dc9-8f6de9e57b9f.png)
这里的样式是不是出问题了？

**Comment by ssshooter** [comment]
什么情况下出现？

**Comment by wuxiaobin1995** [comment]
`<template>
  <div class="container">
    <div id="map" :style="{ width: '1000px', height: '500px' }"></div>
  </div>
</template>

<script>
import MindElixir, { E } from 'mind-elixir'

export default {
  mounted() {
    const options = {
      el: '#map',
      direction: MindElixir.LEFT,
      data: MindElixir.new('new topic'), // create new map data
      draggable: true, // default true
      contextMenu: true, // default true
      toolBar: true, // default true
      nodeMenu: true, // default true
      keypress: true, // default true
      locale: 'zh_CN', // [zh_CN,zh_TW,en,ja,pt] waiting for PRs
      overflowHidden: false, // default false
      primaryLinkStyle: 2, // [1,2] default 1
      primaryNodeVerticalGap: 15, // default 25
      primaryNodeHorizontalGap: 15, // default 65
      contextMenuOption: {
        focus: true,
        link: true,
        extend: [
          {
            name: 'Node edit',
            onclick: () => {
              alert('extend menu')
            }
          }
        ]
      },
      allowUndo: false,
      before: {
        insertSibling(el, obj) {
          return true
        },
        async addChild(el, obj) {
          await sleep()
          return true
        }
      }
    }

    const mind = new MindElixir(options)
    mind.init()
  }
}
</script>

<style lang="scss" scoped>
.container {
  position: relative;
}
</style>`

**Comment by wuxiaobin1995** [comment]
~~~
<template>
  <div class="container">
    <div id="map" :style="{ width: '1000px', height: '500px' }"></div>
  </div>
</template>

<script>
import MindElixir, { E } from 'mind-elixir'

export default {
  mounted() {
    const options = {
      el: '#map',
      direction: MindElixir.LEFT,
      data: MindElixir.new('new topic'), // create new map data
      draggable: true, // default true
      contextMenu: true, // default true
      toolBar: true, // default true
      nodeMenu: true, // default true
      keypress: true, // default true
      locale: 'zh_CN', // [zh_CN,zh_TW,en,ja,pt] waiting for PRs
      overflowHidden: false, // default false
      primaryLinkStyle: 2, // [1,2] default 1
      primaryNodeVerticalGap: 15, // default 25
      primaryNodeHorizontalGap: 15, // default 65
      contextMenuOption: {
        focus: true,
        link: true,
        extend: [
          {
            name: 'Node edit',
            onclick: () => {
              alert('extend menu')
            }
          }
        ]
      },
      allowUndo: false,
      before: {
        insertSibling(el, obj) {
          return true
        },
        async addChild(el, obj) {
          await sleep()
          return true
        }
      }
    }

    const mind = new MindElixir(options)
    mind.init()
  }
}
</script>

<style lang="scss" scoped>
.container {
  position: relative;
}
</style>
~~~

**Comment by ssshooter** [comment]
https://codesandbox.io/s/mind-elixir-vue-nqjjl
没问题吧
