### ISSUE TITLE
typescript 支持

### ISSUE THREAD

**Issue by AshenBird** [ssshooter/mind-elixir-core#68]
能否再在发布的包中提供类型信息

**Comment by ssshooter** [comment]
其实类和实例的类型还在想怎么定义比较好，现在用 prototype 不太方便

**Comment by AshenBird** [comment]
> 其实类和实例的类型还在想怎么定义比较好，现在用 prototype 不太方便

这是个问题，这种方式确实不太利于类型推导，我比较少采用这种方式，是不是可以为采用这种方式的位置使用断言，来辅助类型推导。

**Comment by ssshooter** [comment]
`d.ts` files were not extracted from logic code when this issue was created. i think this issue can be solved easier than before, but i haven't study how to export `d.ts` to npm package.
