### ISSUE TITLE
好不好实现向下和向上分支的思维导图啊？

### ISSUE THREAD

**Issue by zgpnuaa** [ssshooter/mind-elixir-core#71]
目前思维导图可以向左右分支，有时候需要作向下分支发散的图，不知道好不好实现。
比如下面这种
![image](https://user-images.githubusercontent.com/38033949/144866758-65126a6c-32de-4adc-8a56-3ece8d27a9c8.png)
![image](https://user-images.githubusercontent.com/38033949/144866827-84da2c7b-e2c2-4b52-930f-f92f529a294d.png)

**Comment by ssshooter** [comment]
比较麻烦，而且连线做到这么灵活更难😂

**Comment by zgpnuaa** [comment]
> 比较麻烦，而且连线做到这么灵活更难😂

噢噢，没事慢慢来，你做得已经很棒了😆
