### ISSUE TITLE
加载数据后，出现编辑错误

### ISSUE THREAD

**Issue by bluesaiz** [ssshooter/mind-elixir-core#73]
版本：mind-exlixir 0.18.1
重新加载导出的思维数据，然后选中一个子节点，然后按回车键，报错，界面无反应。按Tab键后，不再报错，正常编辑。
![image](https://user-images.githubusercontent.com/40681310/148145635-1093d46a-3d15-446f-a93c-7a0bd8e24e6a.png)

**Comment by ssshooter** [comment]
提供一下重现链接？

**Comment by bluesaiz** [comment]
https://codesandbox.io/s/mind-elixir-react-forked-fj63x?file=/index.js
![image](https://user-images.githubusercontent.com/40681310/148161273-c9c5cdb6-3caf-4bb4-85a9-398038ebe690.png)

感觉是不是这段代码的使用有问题。

**Comment by ssshooter** [comment]
是我的锅，0.18.2 修好了😂

**Comment by bluesaiz** [comment]
好的，非常感谢
