### ISSUE TITLE
expand event handling

### ISSUE THREAD

**Issue by g150446** [ssshooter/mind-elixir-core#77]
I like your work very much and I use this library for my project.
I want to respond for children expansion event. I know can use "bus.addListener" to respond to the events like edit and select. But not expansion event at this time. Please add this event to the list of observing events.

**Comment by ssshooter** [comment]
0.19.1 updated
```javascript
mind.bus.addListener('expandNode', node => {
  console.log('expandNode: ', node)
})
```
