### ISSUE TITLE
最新版 release 0.19.0没有找到mind-elixir.js

### ISSUE THREAD

**Issue by zgpnuaa** [ssshooter/mind-elixir-core#78]
用MindElixirLite.js好像不行啊， 0.19.0版的mind-elixir.js在哪个位置啊？
MindElixirLite.js和mind-elixir.js有什么区别啊？
MindElixirLite.js能直接使用吗？有没有demo啊？

**Comment by ssshooter** [comment]
用 `MindElixir.js`，这个文件没有上传到 `/dist`，但是 npm 里有的
