### ISSUE TITLE
VUE3 编辑器报错 浏览器反馈有这个错误

### ISSUE THREAD

**Issue by jooler** [ssshooter/mind-elixir-core#79]
<img width="1180" alt="微信截图_20220218150958" src="https://user-images.githubusercontent.com/25960405/154635000-a762e4ff-dca2-4415-8d9f-616cff2c3199.png">
<img width="972" alt="微信截图_20220218151032" src="https://user-images.githubusercontent.com/25960405/154635008-7659bc3a-7541-425f-aca4-d01e1c4a4ea7.png">

下面是我的页面
<img width="776" alt="微信截图_20220218151218" src="https://user-images.githubusercontent.com/25960405/154635238-586835fa-1eba-42cd-9a5c-c1752187c0ed.png">

**Comment by ssshooter** [comment]
请问安装了哪个版本？

**Comment by jooler** [comment]
啊 不好意思 我没有注意 好像不支持vue3么？我是npm安装的，"mind-elixir": "^0.19.1",

**Comment by ssshooter** [comment]
> 啊 不好意思 我没有注意 好像不支持vue3么？我是npm安装的，"mind-elixir": "^0.19.1",

不会呀，对框架没有要求的

**Comment by ssshooter** [comment]
https://codesandbox.io/s/mind-elixir-vue3-4ctovl
代码完全一样的呀🤣

**Comment by jooler** [comment]
> https://codesandbox.io/s/mind-elixir-vue3-4ctovl 代码完全一样的呀🤣

运行失败啊哥

**Comment by jooler** [comment]
> https://codesandbox.io/s/mind-elixir-vue3-4ctovl 代码完全一样的呀🤣

哈哈 抱歉，检查出来是我的问题。。。 新建了一个页面整就没有问题
