### ISSUE TITLE
Some Lines are not displayed

### ISSUE THREAD

**Issue by g150446** [ssshooter/mind-elixir-core#80]
![Screenshot_20220220-131726_Chrome](https://user-images.githubusercontent.com/3949656/154828235-553a9a41-c7a7-4b81-93ed-8016a2c1f62e.jpg)

Sometimes lines which connect nodes are not displayed. This often happens on nodes at the bottom. I think it is a bug. I will be glad if you have time to modify.

**Comment by ssshooter** [comment]
It's a rendering problem, but I don't have any solution for now 😭

**Comment by g150446** [comment]
I am very sad to hear that you don't have solution . I think this bug is not fatal, but bad looking. I hope you find solution.

**Comment by ssshooter** [comment]
good news, i have fixed this problem, please update to v0.19.2

**Comment by g150446** [comment]
Thank you for fix! I am very satisfied with your code😂
