### ISSUE TITLE
How to change node color without node Menu.

### ISSUE THREAD

**Issue by g150446** [ssshooter/mind-elixir-core#81]
I want to change font color without node Menu and try the codes below.

this.ME.currentNode.style.color ="#FF0000";
this.ME.updateNodeStyle( this.ME.currentNode );
this.ME.refresh();

These codes caused error with the message "TypeError: Cannot read properties of null (reading 'style')"

Please teach me how to change color.

**Comment by ssshooter** [comment]
```javascript
instance.currentNode.nodeObj.style={color:"#cccccc"}
instance.refresh()
```
PS. if you don't select a node, currentNode is `null`

**Comment by g150446** [comment]
Thank you! It worked! I didn't think that the currentNode has another nodeObj.
