### ISSUE TITLE
请问右键扩展的菜单点击后怎么关闭菜单

### ISSUE THREAD

**Issue by chfcxc** [ssshooter/mind-elixir-core#84]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/35065925/155949619-8a74df61-fcb6-485d-a098-ff48cd50306b.png">

**Comment by ssshooter** [comment]
点击菜单以外的地方

**Comment by chfcxc** [comment]
可以像菜单其他的选项一样点击后直接关闭菜单吗，不用触发点击事件后再点击菜单以外的地方才能隐藏
