### ISSUE TITLE
bug! before  [func](el, obj)   two params are undefined，when keypress

### ISSUE THREAD

**Issue by ups-and-downs** [ssshooter/mind-elixir-core#86]
src/plugin/keypress.ts   `mind.insertSibling()`
Should be amended to?  `mind.beforeHook(mind.insertSibling)`

**Comment by ssshooter** [comment]
do you get any error messages?

**Comment by ups-and-downs** [comment]
before: {
    insertSibling(el, obj) {
    // 快捷键成功触发时 el，obj两个参数都为空
      return true
    },
    async addChild(el, obj) {
      await sleep()
      return true
    },
  },

**Comment by ssshooter** [comment]
`el` is `null` means `el === this.currentNode`
