### ISSUE TITLE
v0.19.4 -- TypeError: Cannot set properties of undefined (setting 'parent')

### ISSUE THREAD

**Issue by SindenDev** [ssshooter/mind-elixir-core#92]
TypeError: Cannot set properties of undefined (setting 'parent')
s
http://localhost:3086/mf-dep_vendors-node_modules_mind-elixir_dist_MindElixir_js.a2615e8a.async.js:9:30338
ue.init
http://localhost:3086/mf-dep_vendors-node_modules_mind-elixir_dist_MindElixir_js.a2615e8a.async.js:9:66426
MindMap._this.initMindElixir
.ant-design-pro/src/components/MindMap/index.jsx:68

**Comment by ssshooter** [comment]
could you offer a codesandbox.io link in which you reproduce this error?
