### ISSUE TITLE
contextMenuOption 如何自定义菜单，或重写先有功能

### ISSUE THREAD

**Issue by Sumnus00** [ssshooter/mind-elixir-core#93]

**Comment by ssshooter** [comment]
配置里加：
```javascript
contextMenuOption: {
    extend: [
      {
        name: 'Node edit',
        onclick: () => {
          alert('extend menu')
        },
      },
    ],
  }
```

**Comment by Sumnus00** [comment]
好吧 感谢 ,extend 是扩展的 原生 的有些想进行修改不知道如何操作。
![image](https://user-images.githubusercontent.com/17699996/165055826-aeb1968c-55c4-4029-83fd-6f7da1de1a50.png)

**Comment by ssshooter** [comment]
要改这个文件 https://github.com/ssshooter/mind-elixir-core/blob/develop/src/plugin/contextMenu.ts
