### ISSUE TITLE
哥，很不好意思打扰你，节点修改的问题困扰我很久了。

### ISSUE THREAD

**Issue by Sumnus00** [ssshooter/mind-elixir-core#94]
![image](https://user-images.githubusercontent.com/17699996/165132343-a53f7834-543d-4c2c-a52f-e3ea3775896b.png)
节点数据是这样修改么？修改完后页面该节点的值还是进入finishEdit前的值，不知道如何操作

**Comment by ssshooter** [comment]
这两句都不用写，会自动刷新的😂
