### ISSUE TITLE
自己怎么实现专注功能

### ISSUE THREAD

**Issue by yihuaiahi** [ssshooter/mind-elixir-core#96]
![QQ图片20220513215709](https://user-images.githubusercontent.com/23310461/168299981-476baa5c-9472-41a8-898b-d7eb2e2ba4b6.png)

## 点击树形结构的spring-boot怎么显示和专注一样的功能，有没有提供专注的方法

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/2a497141d959879b626fff99c80ae86589f39109/src/interact.ts#L233

调用这个函数

**Comment by yihuaiahi** [comment]
感谢大佬
