### ISSUE TITLE
大佬不是可以创建超链接吗？怎么创建和编辑超链接啊！界面上没有看到可以操作超链接的啊？

### ISSUE THREAD

**Issue by yihuaiahi** [ssshooter/mind-elixir-core#98]

**Comment by ssshooter** [comment]
https://github.com/ssshooter/mind-elixir-core/blob/4b5183ae6ff4b29524c2f76e111014b9b9788b24/src/exampleData/1.js#L153

是可以，数据里加 hyperLink 就行了，但是插件没支持

**Comment by zgpnuaa** [comment]
> 

右键菜单里可以加上填写链接地址的功能吗
@ssshooter
